### ISSUE TITLE
Selling Drugs to High Rollers

### ISSUE THREAD

**Issue by BillChirico** [New-Chance-RP/Feedback#246]
<h2>Feature you are requesting.</h2>

Rockford Hills selling to NPC's there should pay a lot more for drugs, but have a higher chance of calling the police.

<h2>What are the benefits to your feature?</h2>

Increase drug sale price, but at a higher risk.

<h2>Anything to support your feature request?</h2>

N/A

**Comment by jimmydesilva** [comment]
I like this idea, because right now people have an incentive to wait for the police to go offline. If you'd make more money with more cops on you'd turn that incentive around, so taking more risks would get you higher gains. You also wouldn't need to increase the chance of civies calling the police then, because if there are more cops on the chance increases that one will respond to the call.

**Comment by Senlarus** [comment]
This was declined in discussions with admins.
