### ISSUE TITLE
Percentage increase on drug sells depending on how many cops are on.

### ISSUE THREAD

**Issue by iamrayuu** [New-Chance-RP/Feedback#259]
<h2>Feature you are requesting.</h2>

I believe the current prices for drugs should be significantly lowered, but at the benefit of a percentage increase depending on how many cops are on duty. 

<h2>What are the benefits to your feature?</h2>

It makes sense in roleplay to perhaps charge more to your clients for if theres additional risks. And more cops DEFINITELY equal more risk.

<h2>Anything to support your feature request?</h2>

N/A

**Comment by jimmydesilva** [comment]
I don't think drug prices should be lowered, but like the rest of the idea, because right now people have an incentive to wait for the police to go offline. If you'd make more money with more cops on you'd turn that incentive around, so taking more risks would get you higher gains (or caught quicker). You also wouldn't need to increase the chance of civies calling the police then, because if there are more cops on the chance increases that one will respond to the call.

**Comment by Senlarus** [comment]
This was denied in discussion with the admin team.
