### ISSUE TITLE
Car dealership not giving vehicles

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#261]
<h2>What bug have you found?</h2>

I had around 7K in my bank and went to purchase a BF400 the dirtbike, i purchased it and it took my money but the vehicle never spawned in. 

<h2>What do you expect should happen?</h2>

Pay money for the vehicle and it should spawn and let you drive away.

<h2>Anything to support your bug report?</h2>

https://www.youtube.com/watch?v=V6GcM8NcHeQ&feature=youtu.be

**Comment by Senlarus** [comment]
check peaceful street garage

**Comment by YahhDopey** [comment]
Did you have a bike rented at the time? 

I had the same issue with the same vehicle (BF400), I checked three garages in the city with no luck. I also had a bicycle rented at the time of purchase, not sure if that could be interfering with it.

**Comment by Senlarus** [comment]
I cannot reproduce this issue. Might have been due to us restarting the script while we were adding more locations and working on the previous license plate issue. Going to close, add more info if it happens again.
![image](https://user-images.githubusercontent.com/1503963/83344232-d3976380-a2d1-11ea-80cd-40937a884d59.png)
