### ISSUE TITLE
Vending Machine options out of order.

### ISSUE THREAD

**Issue by Scarfninja** [New-Chance-RP/Feedback#267]
<h2>What bug have you found?</h2>

Instead of the options being 1, 2, 3 they're showing up as 1, 3, 2.

<h2>What do you expect should happen?</h2>

To not feel dyslexic trying to get my snacks.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/6095886/83219940-aa46ce00-a13f-11ea-8b3f-240301e0d0e9.png)

**Comment by Senlarus** [comment]
This seems to be random, I had it happen to me a few times and then not at all.

**Comment by Senlarus** [comment]
After looking into the code I found where this is happening but it is a dynamic function so in order to get them to be in order I would have to hard code every option for every machine which would make it harder to expand on this system in the future. So for now, I'm going to say that this is going to have to stay this way.
