### ISSUE TITLE
Mod Shop/Mechanic

### ISSUE THREAD

**Issue by Fat-Nick** [New-Chance-RP/Feedback#333]
<h2>Feature you are requesting.</h2>

Pretty self-explanatory, just would like to have mod shops put in the game since the alpha is now at the stage where people have a healthy amount of excess money. This would be the place where players can take their cars to have the cosmetics or the performance changed.

<h2>What are the benefits to your feature?</h2>

I don’t see any negatives that would come along side this implementation. The biggest positive in my opinion, is that police can't recognise your car as often as they do now since you'd be able to switch up the cosmetics. Also, it would add some more individuality to the server since Simeons standard paint jobs are getting a little tame.

**Comment by BillChirico** [comment]
This would be great as a player owned business as well once they implement that

**Comment by BillChirico** [comment]
> I feel like when I first joined before alpha I heard they had plans for multiple player owned mechanic shops, but that was a future plan and not for alpha.

I believe that is the case as well if I remember correctly.

**Comment by Senlarus** [comment]
We all agree, the problem is that we don't have a good starting point for this script. Everything we have tried has been scuffed as hell. So when, yes when, we introduce this it will come with a lot of issues. We wanted to get to a point where people could play on the server and this feature isn't 100% necessary for RP to begin. We are targeting this for post alpha unless people feel it is worth pushing back the alpha launch to get in.

**Comment by Monster-Duck** [comment]
I think it could come after alpha but maybe in the meantime do like the GTA Online mech shop?

**Comment by bloombydee** [comment]
@Monster-Duck we did originally have something similar to online but even that has issues that need ironing out, someone got stuck inside the garage etc.

**Comment by bloombydee** [comment]
Implemented :)
