### ISSUE TITLE
Phones Show the Actual in-city Time

### ISSUE THREAD

**Issue by Birlzey** [New-Chance-RP/Feedback#344]
<h2>Feature you are requesting.</h2>

In-city time shown on your phone.

<h2>What are the benefits to your feature?</h2>

I think it would be more intuitive and enable the flow of some RP better, e.g "meet me round the back of Digital Den at 1 am" you could just open your phone and check the in-city time. Not sure if this is an easy implementation or not but I would like to see it and I'm sure other people would. I just dislike having to press ESC and wait for it to load the normal way, very inconsistant imo.

<h2>Anything to support your feature request?</h2>

None

**Comment by Senlarus** [comment]
The main reason for the phone showing your local time is so you can know how long ago(IRL) people have posted tweets or yellow pages ads. This matters because if someone says they have started doing Taxi and are offering rides you'd want to know how long ago that was in real time. So for that reason, we will keep it the way it is.
