### ISSUE TITLE
Picture Messages 

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#444]
<h2>Feature you are requesting.</h2>

The ability to send a photo/photos in a message. I have also been thinking a way to impliment this into the darknet, So in past cities it was just texted based and they were just so messy.. phone numbers all over which is a bit silly. Having the ability to post photos on the darknet would be pretty cool and lowkey. 

<h2>What are the benefits to your feature?</h2>

Massive RP potentional imo, little things mean a lot.

<h2>Anything to support your feature request?</h2>

Nope, idea iv had for a while would love to see what people think and add more to it!

**Comment by Senlarus** [comment]
We had this on the server but the issue is that it is extremely unreliable. There are many issues that can result from having this option from getting locked into the animation to having the phone script totally error out. At a later date I can potentially go in and add some error handling for when the image doesn't save to make sure people don't get stuck. It won't make the feature work 100% of the time, but I can make it not cause the resulting issues when it doesn't. Stay tuned post launch for possible progress on this.

**Comment by Senlarus** [comment]
Merging with #452
