### ISSUE TITLE
EMS Garage Vehicle Selecting Rapidly Closing | Getting stuck in the Vehicle during Assigning

### ISSUE THREAD

**Issue by lAmantel** [New-Chance-RP/Feedback#446]
<h2>What bug have you found?</h2>

There is a EMS Cadet, who is having issues assigning a ambulance. He goes upstairs, enters the menu. It then takes him downstairs to where he views the ambulance,  he goes to assign it and gets stuck bouncing up in down. He said It tells him it's been assigned to him but when he goes downstairs to spawn it, It kicks him out of the garage menu giving him no time to select a vehicle. I myself have been having the issue where it kicks me out of the menu when trying to select my EMS vehicle.

<h2>What do you expect should happen?</h2>

I think that when he goes to assign the ambulance, instead of taking him all the way downstairs to "View" it. It just assigns, as if you were logging onto the computer and logging that the ambulance is yours. I also think that when you go downstairs to access the ambulance from the circle if it would stay opened and no close out rapidly. It doesn't give any time to select a vehicle.

<h2>Anything to support your bug report?</h2>

I have no image or video at the moment of the issue happening myself, but I do have a screenshot of his F8 Menu, and the only error code he has.

https://i.imgur.com/JEd70zB.png

**Comment by Senlarus** [comment]
Vehicle assignment... interesting. This is a different script than the garages. I'll have a look.

**Comment by DerkDuece** [comment]
https://clips.twitch.tv/SourEnticingCucumberOSkomodo
PD.

**Comment by Senlarus** [comment]
I've been so checked out mentally lately that... I pushed a fix for this issue two days ago but I never pulled it onto the server. SO yeah... I just pulled it and restarted the script. It's fixed according to all of my testing. Please let me know if you run into any other issues.

**Comment by bloombydee** [comment]
@Senlarus seems the issue with the vehicle assignment is the garage conflicting with it, the garage keeps trying to store preview vehicles or doing checks or something

**Comment by Senlarus** [comment]
Ok, I will look into the vehicle preview part of the garage script but I don't think that is causing issues with vehicle assignment. From what I can tell vehicle assignment is working fine. The issue reported was that he got stuck bouncing up and down. That has to do with when you exit the job assignment menu and it teleports you back up to the training room you will be a bit in the air. This persons ped must have gotten stuck in a shrug or bookshelf when they teleported back. This is what I found:

1. Vehicle assignment doesn't get glitched or bugged out due to the presence of any vehicle on the spawn location in the garage. Ghost vehicle or real vehicle, doesn't matter, has no effect.
2. Vehicle assignment issue with jumping up and down related to teleporting ped back to training room. If standing too close to bookcase or plant might get glitched inside of object. Should be able to simply walk out and be fine.
3. Issue with Cadet getting kicked out of garage menu was due to me not pulling a fix I had pushed two days ago. That has been pulled and applied to live. This issue should not longer occur.
4. Garage script doesn't have a vehicle spawn directly on the job assignment preview location. I did that on purpose.
5. Garage script may have issues with not properly cleaning up ghost cars. Not related, separate issue.

The originally reported issue should be resolved now. The jumping up and down part shouldn't be game breaking, hardly even occurs, and is minor enough that I don't feel anything needs to be done at this time. If it becomes a very regular occurrence or results in someone getting completely stuck inside of objects and being unable to get out, we can change location or update coords or remove the vehicle preview. With that being said, I will close this report.
