### ISSUE TITLE
Carry Capacity Limit (drugs)

### ISSUE THREAD

**Issue by BIRLZ95** [New-Chance-RP/Feedback#464]
<h2>What bug have you found?</h2>

You can carry more than the max amount.

For example if you have 100 1g bags(the max), you can exceed that limit by breaking more down as you would.

<h2>What do you expect should happen?</h2>

Not be able to exceed the limit stated in the inventory.

<h2>Anything to support your bug report?</h2>

![image](https://user-images.githubusercontent.com/64453673/91494948-9f701680-e8b1-11ea-801c-2e9eebd9e055.png)

**Comment by Senlarus** [comment]
This is just an issue of numbers. You'll never be able to continue to go over the limit, I think 10 over the most you can go and it's due to how things break out. We can fix this but it will just end up robbing people of drugs or making it so they can only carry 91 before they're not allowed to bag any more. It's not really an issue the way it is as it allows for a bit more flexibility in how you bag stuff.
