### ISSUE TITLE
Discord Design 

### ISSUE THREAD

**Issue by SirLyx** [New-Chance-RP/Feedback#524]
<h2>Feature you are requesting.</h2>

All of this is my own opinion.

Newchance's discord is looking dry, unorganized when it shouldn't be. 
any server's discord server gives a direct impression on the server itself, and new chances definitely deserve better.

For starters the **roles**.
Default colors for the roles just because there isn't enough colors? come on.

I made these just as an example that there are LOTS of options to use from. Take a look.
![sdadasda](https://user-images.githubusercontent.com/69530692/94284101-36cc9600-ff52-11ea-9d75-667bda107e87.PNG)

<h2>What are the benefits to your feature?</h2>

Better looking community discord.

**Comment by GamerDaniel18** [comment]
I do miss the colours already, it gave people individuality, now there's just a huge list of white names, it looks like movie credits (which no one reads), they all blend together and no one stands out. It also makes it awkward to share emails. Just my opinion too 🤷 what do I know lol

**Comment by Senlarus** [comment]
I'm curious what you think about the disorganization. You said "dry, unorganized"
So it it just because of the removal of the colors? Is there more? Something about the channel structure or...?

Also, I genuinely want to hear what people have to say about this...
**Questions for anyone to answer**
_In regards to COLORS_

Consider this basic art principal called color theory. There are 3 primary colors, 3 secondary colors, and six tertiary colors that make up the color wheel. These are colors that are the most distinguishable by the human eye, and the tertiary colors are very close to either thier primary or secondary counterparts... but let's go with best case scenario here.

12 colors is all we really have to work with and we have 22 ranks that would need colors.
We have 7 different staff ranks
We have 6 different supporter ranks
We have 5 different white list jobs
We have 4 different community ranks

- How do we make sure STAFF RANKS & DONATOR RANKS stand out? These roles are for people who go above and beyond just playing here to devote time and resources outside of game to help advance the community. We want to make sure these roles are recognized above the others.

- Discord works on a hierarchy. So when someone has each of their 3 characters in whiltelist jobs... how do we handle colors for them if we give every whitelist job its own color? "Why is *insert job* at the top, why are they more important than everyone else?" "Hey, I'm in two jobs but I really want my name to be RED not ORANGE!" How do we handle that?

- What do we do when we keep adding these types of roles to the discord as the server grows?

**Comment by Senlarus** [comment]
For anyone wanting to accept the challenge, here's a list of the ranks:
**STAFF**
Founder
Senior Admin
Admin
Moderator
Mediator
Staff
Helper

**Supporters**
Gold Supporter
Silver Supporter
Bronze Supporter
Basic Supporter
Supporters
Nitro Booster

**Job Ranks**
LSPD
LSMS
Weazel News
LS Customs
Dynasty 8

**Community Ranks**
Design Team Lead
Design Team
NCRP Streamer
New Chance OGs

**Comment by SirLyx** [comment]
Challenge accepted.

**Comment by GamerDaniel18** [comment]
I think we should look into expanding the visual range of humans, if we could see more of the light spectrum we'd be able to have more ranks. Let's get the boys down in the lab to work on it 👨‍🔬 😂

**Comment by jimmydesilva** [comment]
Staff, blue. Supporters, yellow. Jobs, red. Community ranks, purple.

Aaaand argue.

**Comment by Tekoro** [comment]
Hello, just wanted to chip in. It's difficult to find a good color scheme, but these are all different colors following categorization.
The only category of roles that can be shaded is the admin, snr admin and moderator one, but oh well.

This is mostly an example that you can use lots of shades and still have distinct roles that will be recognized, you don't have to like this one since it was a rushed ex., but know that it can be done. 👍 
<a href="https://imgur.com/2wluJza"><img src="https://i.imgur.com/2wluJza.png?1" title="source: imgur.com" /></a>
<a href="https://imgur.com/TCzC0uS"><img src="https://i.imgur.com/TCzC0uS.png?1" title="source: imgur.com" /></a>
<a href="https://imgur.com/kYZBCYW"><img src="https://i.imgur.com/kYZBCYW.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/48naKAT"><img src="https://i.imgur.com/48naKAT.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/PR8XfP2"><img src="https://i.imgur.com/PR8XfP2.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/h8JAyoG"><img src="https://i.imgur.com/h8JAyoG.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/d0CaF7n"><img src="https://i.imgur.com/d0CaF7n.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/2mIn21t"><img src="https://i.imgur.com/2mIn21t.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/8fpEXze"><img src="https://i.imgur.com/8fpEXze.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/TJup6wi"><img src="https://i.imgur.com/TJup6wi.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/2qqeXuD"><img src="https://i.imgur.com/2qqeXuD.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/aDdGzK9"><img src="https://i.imgur.com/aDdGzK9.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/qWS9P7c"><img src="https://i.imgur.com/qWS9P7c.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/YboPJq2"><img src="https://i.imgur.com/YboPJq2.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/bTK31sX"><img src="https://i.imgur.com/bTK31sX.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/zEJUeOC"><img src="https://i.imgur.com/zEJUeOC.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/QTUavPW"><img src="https://i.imgur.com/QTUavPW.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/kyD05Wu"><img src="https://i.imgur.com/kyD05Wu.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/c2RXoKn"><img src="https://i.imgur.com/c2RXoKn.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/rk7yy1Z"><img src="https://i.imgur.com/rk7yy1Z.png" title="source: imgur.com" /></a>

**Comment by Senlarus** [comment]
I think some of these concepts can help reduce the number of colors needed. We already did a shading or brightness change approach with the supporter ranks so that way supports are all a shade of yellow and they just get a bit brighter as they go up. I do appreciate your creativity with the names lol Weazel news is the best!

**Comment by GamerDaniel18** [comment]
Wow, Tekoro, A+ for effort and presentation!  
(Also... Where IS Spiderman?.. Get me some damn pictures of spiderman!) 
![image](https://user-images.githubusercontent.com/50466883/94325913-c6953300-ff98-11ea-84ec-6e4fb765dd54.png)

**Comment by BIRLZ95** [comment]
More food for thought! 😘
![discord roles template](https://user-images.githubusercontent.com/64453673/94340365-04c23f00-fff9-11ea-8955-bbe76fd353b5.png)

**Comment by Tekoro** [comment]
That's good, maybe keep Nitro Booster pink as it's default color, make LSMS red since it's not being used in your scheme, male LS Customs orange? pgood shading overall

**Comment by SirLyx** [comment]
For the discord channel structure, here is a prototype on what It can look like in comparison to the current layout.
Current one :
![old one #1](https://user-images.githubusercontent.com/69530692/94340916-e0b92a80-0005-11eb-8c39-4794ed8b5c17.PNG)
New one : 
![New one #1](https://user-images.githubusercontent.com/69530692/94340920-ef9fdd00-0005-11eb-8dc4-491c1bd677b1.PNG)

Current one :
![old one #2](https://user-images.githubusercontent.com/69530692/94340927-fb8b9f00-0005-11eb-8c50-d44ecf60b3d8.PNG)
New one : 
![new one #2](https://user-images.githubusercontent.com/69530692/94340929-00e8e980-0006-11eb-8057-001ad7c6d74c.PNG)

For the role colors, I tried to stick to newchance's color theme, red, orange, and yellow.
![Founder](https://user-images.githubusercontent.com/69530692/94340954-1c53f480-0006-11eb-856e-a4f908400837.PNG)
![senior admin](https://user-images.githubusercontent.com/69530692/94340956-1eb64e80-0006-11eb-8392-eea6dc49d65c.PNG)
![admin](https://user-images.githubusercontent.com/69530692/94340982-49080c00-0006-11eb-8f31-f64b2e674429.PNG)
![moderator](https://user-images.githubusercontent.com/69530692/94340985-4c02fc80-0006-11eb-8bc1-ee4bbcc3bc5d.PNG)
![Madiator](https://user-images.githubusercontent.com/69530692/94340986-4d342980-0006-11eb-8413-53dc9cb4f15b.PNG)
![helper](https://user-images.githubusercontent.com/69530692/94340988-4e655680-0006-11eb-89db-119e5471a84b.PNG)

![Roles](https://user-images.githubusercontent.com/69530692/94341007-5e7d3600-0006-11eb-8418-c4faa4430c1f.PNG)

**Comment by Senlarus** [comment]
Good suggestions, keep 'em coming. We will review and discuss these at our next founders meeting.

**Comment by SirLyx** [comment]
forgot to put in the server template 
here It is https://discord.new/uTUtYHF9SC5c

**Comment by Senlarus** [comment]
Colors restored, yay!
