### ISSUE TITLE
/BODYCAM for PD?

### ISSUE THREAD

**Issue by Alizz07** [New-Chance-RP/Feedback#557]
<h2>Feature you are requesting.</h2>

*I think that a /bodycam command to bring up a lil overlay on a PD or EMS screen incase anything happens and we need proof, also is cool for streamers to show their callsign and stuff like that*

<h2>What are the benefits to your feature?</h2>

if something happens which needs government proof it is easier than having to have your phone out, also cool for streamers to have if they're streaming PD or EMS they can have a little overlay to show their callsign.

**Comment by timmy-timm** [comment]
You guys should add a non lethal shot gun, the bean bag shotgun. It’s bright orange and acts like a taser.

**Comment by Senlarus** [comment]
We've discussed this and we do not want to allow the usage of in-game footage for in-character things since a lot of players don't have this capability available. Where a bodycam/gopro is something that is easily obtainable, not everyone's PC is easily capable of recording. We want to keep things as even as possible which is what led to this decision.
