### ISSUE TITLE
Selling the drugs after optimizations feels a bit scuffed

### ISSUE THREAD

**Issue by Ic3BoxTheSuspect** [New-Chance-RP/Feedback#589]
<h2>What bug have you found?</h2>

So basically, I have noticed the following things:
- I have to spam the H button, pressing only once works in only like 1% of the cases (at least for me).
- I also have to face the local directly most of the times. Being behind him won't trigger the sale anymore.
- The notification that appears in the left bottom side will remain over there for a decent couple of extra seconds even if there isn't a local anymore next to you. This could create confusion if another local is walking in that time frame next to you and you already sold to that one, for example.

<h2>What do you expect should happen?</h2>

To be able to sell to the local even if I'm behind him (he will turn towards me), to be able to sell without spamming the H key, and the notification to be there in the exact time frame when you are next to a local that you are able to sell to.

<h2>Anything to support your bug report?</h2>

N/A

**Comment by BillChirico** [comment]
Also, was the rejection rate raised?

**Comment by Ic3BoxTheSuspect** [comment]
I haven't noticed that to be honest. The rejection rate feels the same to me. You can be lucky and sell 9 bags to 3 locals one after another or get rejected 3 times in a row.

**Comment by BillChirico** [comment]
> I haven't noticed that to be honest. The rejection rate feels the same to me. You can be lucky and sell 9 bags to 3 locals one after another or get rejected 3 times in a row.

Id love to see the prices scale based on police presence. I've noticed a higher rejection rate unless I was unlucky

**Comment by Ic3BoxTheSuspect** [comment]
Some people just sell when there aren't cops clocked on. So yeah, maybe rewarding with an extra $20 or something per bag if the cops are clocked on and you are selling wouldn't be a bad idea.

**Comment by staxstefan** [comment]
I believe it makes all the sense to directly face someone in order to sell something. 
In my opinion, increasing bag price when cops are around or not makes no sense as "city always have police officers on a standby" Drug prices should always be the same following IRL logic.

- Regarding being rejected many times, I'm not wise about, however, by logic if you see 10 people constantly being on the same street all day long selling drugs that area will eventually make civilians not buy more bags as they already have during that day. 

* Note this is all just pure opinionated comment, does not actually describe how the current system works.

**Comment by Ic3BoxTheSuspect** [comment]
You can tap someone on the shoulder and they will turn towards you tho'. You never sold to them while they weren't facing you. Even before, they would turn towards you.

So the action of selling the drugs was done while facing them directly anyway.

**Comment by Senlarus** [comment]
We have to make sacrifices for optimization. Nothing about the script was modified except the timing which is why you are seeing the issue with having to spam the H key. I can increase the time a bit to remove that.
