### ISSUE TITLE
more vehicles

### ISSUE THREAD

**Issue by Alizz07** [New-Chance-RP/Feedback#596]
<h2>Add on vehicles</h2>

*Add on cars, i know some are getting added soon but i am requesting these too just because why not.*

<h2>More vehicles to choose from :)</h2>

<h2>https://www.gta5-mods.com/vehicles/ubludock-vehicles-pack-add-on there are 50 add on vehicles i think would be sick to have in this city.</h2>

**Comment by MorganJames01** [comment]
I have used these before and some of the models are rushed and low quality and bodywork is just stickers, some wonky textures too, there are lots of new cars on the way and they are all gonna look great. Once these are in I suggest then that u make a GitHub with suggested cars because there is a chance that some of the cars in that pack is all ready being added. But nobody knows yet :D

**Comment by driftoooo** [comment]
Hi! **A lot** of addon-vehicles are currently in the works. I've looked at the pack you've suggested myself and a fair amount of the models are either rushed, incomplete, or lacking in bodywork (As Morgan also stated). Thank you for the suggestion! We're trying to stick to models from particular well-known and trusted creators, however, feel free to throw a request for a car or two. 

Thanks again!
