### ISSUE TITLE
2017 Nissan GTR

### ISSUE THREAD

**Issue by Mubbb** [New-Chance-RP/Feedback#600]
<h2>What are you requesting?</h2>

**1) - Vehicle addition -** *https://www.gta5-mods.com/vehicles/2015-nissan-gtr-nismo-yca-y97y*
I do have everything already unpacked and working + a better custom handling line available upon request if needs be.

<h2>Why are you making this request?</h2>

Just an additional import + tuneable + very noice.

**Comment by driftoooo** [comment]
Hi there! Thank you for the suggestion! We currently have a line of custom cars that I'm going through at the moment, each coming with individual custom handling so that we can avoid issues that were caused by using a particular handling method with the F&F pack. You'll have to wait and see in regards to this vehicle, I've personally used this model before in an unrelated personal project I was doing and I know that the model is of good quality. I'm unable to disclose whether or not this vehicle will be used, however, we'll take it into consideration. 
Thanks again :)
