### ISSUE TITLE
Removal of Bullet Proof Car

### ISSUE THREAD

**Issue by shadowviper0** [New-Chance-RP/Feedback#609]
<h2>What are you requesting?</h2>

Rumbo that is currently in is bullet proof and gives advantages for Crims to get out of situations by not being shot staying in it.

**Vehicle removal -** Rumpo

<h2>Why are you making this request?</h2> It seems unfair to law enforcement or other crims to have a bullet proof van that cant be penetrated. Knowing cops can't have bullet proof cars, it seem it is overpowered for them to have one.

* - What improvements / benefits do you think this will have and why?* It will give a fair playing ground and not having a thing to use a leverage of something that no cop can penetrate or deal with. It prevents people from being able to not fear their life in a car that is bullet proof.

<h2>Anything to support the above?</h2>N/A

**Comment by greed702** [comment]
It's bullet resistant not bullet proof. It will stop some shots but not many.

**Comment by shadowviper0** [comment]
When we dealt with situation, it was full bullet proof. Shotgun didnt touch subject at all.

**Comment by charlie225** [comment]
It will break after a certain amount of bullets also u only fired like 2 shotgun bullets at it

**Comment by MorganJames01** [comment]
Hey, the Rumpo Utility is known for its 'bulletproof windows' in fact they are **Bullet resistant** this means that we are able to remove the Resistance or make it stronger and the vehicle is not as bulletproof as it seems, although it takes maybe around 4 shotgun shots to break a window on it. (shooting in the same spot) if you shoot a shotgun at it some of the pellets from that shotgun go through the window therefore damaging those behind it (this is because they are NOT bulletproof, they are bullet resistant) and the damage it does may be small but it depends on range etc.etc if you are having problems with a shotgun not destroying the windows of it, you may either be to far away or it could be a bug but from what i have seen in city there is no current bugs with its reinforced windows and if there is let us know. It is supposed to be like that. However if there is lots of complaints about it and people overusing it then maybe we could just remove the resistance or lower it. Hope this answers any of your questions. if not let me know

**Comment by driftoooo** [comment]
What Morgan has said is, for the most part, factually correct, however, there are issues that come with this. Doing this for FiveM will require a lot of additional steps to work, which I will not detail here, however, it's been added to my list. If this was to be done on the base GTA 5 it'd be easy to do, however since it's with FiveM there's a lot of additional steps to make this work. Either way the vehicle should not be fully bulletproof, it is bullet-resistant as stated above. 
Thank you again for the comment, I'll add it to my list. :)

**Comment by driftoooo** [comment]
Closing the issue for now, 
this will be in the works once I'm back from my small break to focus on some things with life. Feel free to re-open if you feel necessary. 
Thank you for the report. We'll have it sorted when I can :)
