### ISSUE TITLE
Temporary Freeze to Drug Supply

### ISSUE THREAD

**Issue by Zopfco** [New-Chance-RP/Feedback#648]
<h2>Drugs are basically free</h2>

Other than the initial investment the drug supply is currently limitless.  It's very low-risk and people have built up insane stashes. I think this is disruptive to the economy & prevents the sort of interaction & conflict that would drive better criminal/gang RP.

<h2>What are the benefits to your feature?</h2>

A temporary freeze would make these stashes more of a focal point and create better lines of RP as different factions & individuals compete for access.  Prices would fluctuate & cut off the endless faucet of easy money. Drug busts and seizures would begin to have an affect when people can no longer infinitely resupply at will.

<h2>Anything to support your feature request?</h2>

In the long term there should be both greater ongoing monetary costs and personal risk involved in drug manufacturing.  The current drug system encourages nonstop grinding, which fosters an attitude where RP is seen as a nuisance that interferes with making easy money.

I also think the supply system in place should have limited uses.  

Sourcing large quantities of drugs should be both expensive and high-risk.

**Comment by Senlarus** [comment]
We're going to discuss this with the staff team and try to decide what we need to change. We appreciate the feedback from our community and have seen the conversation that is going on in general chat.

**Comment by Ic3BoxTheSuspect** [comment]
Getting the drop itself shouldn’t be free in the first place, in my opinion. It should cost at least half of what you are about to make if you sell them. This will provide a risk of losing money if you are caught by the cops, rather than just losing time.

Speaking of coke for example, maybe make it so it would cost A LOT to call a drop, and get large quantities only with it. This would force players who don’t have those funds necessary to call in a drop to seek other “smaller” types of drugs, or interact with people that can afford calling in drops in order to buy product from them. 

This would allow gangs for example to start selling to people more, not only to locals, and it will provide more RP situations overall. This would also give PD more opportunities for raids due to the large quantities that will be moved around.

**Comment by greed702** [comment]
I am 100% on board with this idea. The idea of it costing of the drop itself is a great idea. Cuts back on over saturation, makes more RP situations, makes running them riskier as well. To be honest a free drop is a bit crazy when you think of the profit to loss possibilities

**Comment by ChuckBurn** [comment]
I think other drugs need to be added. However, there is a lot of RP around the drugs. I know some people who have spend hours RPing to create an an illegal drug empire. These people have RP'd to get clients and even some of the biggest gangs as clients. So before you say all the drug being sold on the street are pure profit please put some RP into the drugs.

**Comment by whatsbrackinbruh** [comment]
I don't agree with freezing the whole drug supply even temporarily as this would upset a lot of people I'm afraid but I do however agree with it being way too easy to obtain and get for just about anyone and that does result in a lack of gang/crim RP in terms of conflict with drugs. I feel a better system should be in place than the current one. An idea I've had for a drug system that would bring more RP for everyone who wants to get involved and bring conflict among certain gangs for control over the drug game would be to start off by making it a sort of whitelist job/function between only a handful of trusted gangs that founders/admins could agree on. It's silly to me that anyone could essentially get all the supplies and manufacture/process the drugs themselves as this only results in the same people who make them, sell the drugs on the streets themselves for max profit. The people who get the drugs in bulk should never be the ones selling it in bags, but they should be selling off the bulk to players who then sell it on the streets themselves. Both of which should be making decent profit for both. Crim/Drug RP should always pay more than any public job and some whitelist jobs since it should be something that's high risk/high reward. If, just for example, 2 gangs were given the ability to call in these drugs and process them, that would create conflict and RP for those 2 gangs fighting between territory and customers. It should be something that anyone looking to buy drugs would have to work towards with building their character, getting to know people, making friends and contacts and working their way up to gain the trust of these big gangs to then sell drugs to them. It should never be something that an average player who wants to get into drugs can just get it on the first day in the city within a few hours because anyone can make it themselves and it's too easy to get. It should be who you know and how trusted you are. I also think the idea of someone who wanted to try and fuck over gangs, try to sell on the bulk product for more profit, rat to the police etc. should be blacklisted by those gangs from getting drugs as a result of their actions or kidnapped/killed for trying to rat of them and get police involved. I think making drugs a whitelist function between certain gangs and limiting the supply in the city would create more RP in general for everyone in general. This is just a rough idea of how I feel drugs should work in the city, so... :-)

**Comment by Senlarus** [comment]
I'm just going to say that I don't really agree with hardline restrictions on content like calling in drugs. The idea of only allowing certain groups of people to do something without anyone else having the ability is not my favorite. I do think there are things that we can do that will make it more difficult for solo or new players to do these things however.

I also appreciate everyone taking the time to provide this feedback for us, it's really great to see! Please keep it coming!!

**Comment by whatsbrackinbruh** [comment]
I was just thinking that anyone having the ability to call and and make drugs just doesn't really make sense. I feel like with this being a whitelist server, there should be restrictions on it. It should be hard for your average person to get into as they would have to do a good bit of character building and gain trust amongst the right people. I just personally feel there's more RP/Crim/Gang potential with it being like that. It would also force the people involved whether that's the person trying to get into drugs or the gangs selling them to be more careful about who they know, who they don't know, who they speak to, makes them be more careful when it comes to cops. I think it would also help for a lot of people to grow their character and help with making and maintaining storylines. But I also can see from your point of view why you wouldn't want restrictions. I'd also assume from your thoughts on it, you feel as though other people would be feeling as though it's unfair for their gang who don't have the ability to do it, or there's some sort of favouritism but I would like to get a couple of opinions on this and just see what people think out of curiosity.

**Comment by Ic3BoxTheSuspect** [comment]
The drugs don't have to be whitelisted. If the prices themselves are raised, and lets say to call a drop would cost $200,000 and would give in return **LARGE** quantities of drugs, this will not restrict anybody from anything. Instead, it will force players that do not want to spend this amount of money to seek out and supply themselves from people who do.

Gangs will most likely import these drugs, while "solo riders" will buy from them. New players will not be able to do this at the beggining unless they interact with other people/gangs/groups and buy from them, or they can just go and do another type of drug like weed until they get the amount of money needed.

_Because in real life, you can't really touch this amount of drugs by yourself. Cartels, gangs, groups in general are the ones who import, export the drugs around the world. It's a whole network, somebody is the supplier, somebody else is the person who sells them on the streets._

**Comment by Senlarus** [comment]
@whatsbrackinbruh I do agree with your thoughts on the difficulty. I would just want "anyone" to have the ability to work up to that point through in-game mechanics and discovery, not via some whitelisted status. And yes, one of my main concerns is the potential favoritism but also the potential chokepoint. If one of the whitelisted gangs goes off on a break or just decides to NOT call in drops then the whole server and drug system suffers. I'm a fan of the free market type system where other player groups can move in and take over if they're more active. This keeps things alive naturally without needing constant staff monitoring and intervention.

**Comment by greed702** [comment]
What if we whitelist a "cartel/mob" main focus is importation, processing, and distribution(delivery to gangs or dispensary) . Would be able to provide weed to dispensaries, coke/meth and others to gangs in bulk. Pay would be dirt but % of what is sold to people would be nice. Could even have a "front" as a store to order or something along those lines. Someone would have to create an SOP for it, ran by either admin or trusted person. Would create a ton of RP from haggling, building a report, friendships ect. Would eliminate the anyone can call for a drop but keeps the anyone can buy.

**Comment by Zopfco** [comment]
Have to agree that a whitelist is too restrictive.   That's far too much power to give to one "gang" (or whoever).

Think it might be interesting if the harder drug contacts came from prison.   It presents us with a hard choice for a character so that everyone doesn't become a drug kingpin just because it's the easiest way to get rich.

**Comment by bloombydee** [comment]
About the contact, the plan is to require the player to drag it to the 'use' button, which will then consume the item but allow that player to call in a shipment and that permission would be saved, similar to how a weapons license allows you to access ammunation. Then when a player is sent to jail, it will automatically clear that permission, similar to revoking a license, which will require you to find a new contact. This is to simulate that a drug contact would cut ties with someone that's recently been arrested.

**Comment by Senlarus** [comment]
We have taken this feedback into consideration and leadership has developed a plan forward to make changes to the system to enhance it.
