### ISSUE TITLE
About Chop Shop

### ISSUE THREAD

**Issue by M4R6S** [New-Chance-RP/Feedback#661]
Recommendation
To remove Zentorno and Turismo R from chop shop list.
Make it, so you can chop shop only local vehicles, not player owned ones 
+ It's gonna be easier, because then admins/founders don't need to take care of people, which chop shop them own vehicles

**Comment by Santosnc** [comment]
I'm for making it only for local vehicles.

Maybe not removing the Zentorno and Turismo R from the list because they have a very low spawn rate and almost can never be found and if they have the same spawn rate as the voltic, infernus, bullet. This way the high-end cars don't have to be removed from the list.

**Comment by Senlarus** [comment]
I will be looking into this after I fix the pawn shop.

**Comment by iamrayuu** [comment]
All vapid vehicles are potential vehicles to get on your list, but we have also made it so owned vehicles can be chopped but it will come at a cost. :)
