### ISSUE TITLE
Tackle Function

### ISSUE THREAD

**Issue by Alizz07** [New-Chance-RP/Feedback#667]
<h2>Feature you are requesting.</h2>

a tackle function for LSPD instead of using a taser sometimes you can takle someone if they un towards you

<h2>What are the benefits to your feature?</h2>

cool feature for LSPD 

<h2>Anything to support your feature request?</h2>

Nothing really just something to benifit LSPD

**Comment by BadBritishGamer** [comment]
Hey, appreciate you making this feature request.

The downside to a tackle feature is the fact it is really clunky, because of desync etc it can become quite a hot topic for being over powered.

For example the officer doing the tackle can see themselves right on top of the person they are chasing, but ultimately the person being chased is a good 2-3 metres away which then when tackled it looks like they teleport to the officer.

And because of the above, personally being in PD I don't want it implemented.

**Comment by Senlarus** [comment]
Been brought up a lot, still a no at this time.
