### ISSUE TITLE
Dodge 69 weight + handling

### ISSUE THREAD

**Issue by Fat-Nick** [New-Chance-RP/Feedback#668]
<h2>What are you requesting?</h2>

**Vehicle changes -** make the car heavier in terms of weight, if i crash or get hit while driving, the car does all kind of acrobatic moves. Also to make it a bit better at taking turns, has a real hard time cornering over 50ish mph. Speed related stuff is all good tho.

<h2>Why are you making this request?</h2>

It'll make the car alot more suitable to drive. I cant have any races or chases due to these set backs.

<h2>Anything to support the above?</h2>

n/a

**Comment by driftoooo** [comment]
Will be looked into. Thank you for the report :) I'll keep you posted!

**Comment by driftoooo** [comment]
Still in the works. Trying to figure out why it does this given the bizzarness of the issue, since I’ve gone through all the meta files and nothing made a difference to that particular factor.

However, whilst there I fixed the following:
- Removed it’s hydraulics 
- Edited the centre of mass
- Fixed an issue with performance parts not displaying 
- Changed vehicle sound to a more realistic sound

The changes stated above are live as we speak, I’ll leave this issue open until we resolve the issue at hand. Thank you again for the patience and for your report. I hope to have this sorted for you soon :)
