### ISSUE TITLE
Add no concept GTR

### ISSUE THREAD

**Issue by ChuckBurn** [New-Chance-RP/Feedback#673]
<h2>2020 GTR</h2>
**1) - 2020 GTR R35 -** https://www.gta5-mods.com/vehicles/2020-nissan-gt-r-nismo
**2) - Vehicle removal -** *GTR concept car*
<h2>The concept car is not real. Google 2021 GTR. Same body as 2020.</h2>
More realistic

**Comment by driftoooo** [comment]
Hi. Thank you for the suggestion. Nissan collaborated with Italdesign to create the model, based on the latest Nissan GT-R NISMO, in commemoration of the 50th anniversaries of the GT-R in 2019 and Italdesign in 2018, the car does exist within the world at this point and are aimed to be shipped to customers between 2020-2021. Although the car is not currently available to the general public as it has been shipped yet, we do not see any real reason to remove it from the server. The car has its high price point due to its rarity, being a 1/50 car, I simply made a mistake upon naming the vehicle, as it should be named the "2021 Nissan GTR-50". Anyway, I think simply removing this car is not really an option. However, I do understand you wanting another GTR available in the city. I'm unable to comment on that particular topic, but I hope this answers your questions. Thank you again for the report.
