### ISSUE TITLE
BMW M5 Performance mods

### ISSUE THREAD

**Issue by Whisely3512** [New-Chance-RP/Feedback#678]
What are you requesting?
I am requesting performance mods for BMW M5 F82 because it's currently not tunable at all and it's really drifty no matter what

Why are you making this request?
Because BMW M5 is currently almost undrivable because it's so drifty on the roads, also you can't do anything to fix that , there is no performance mods you can put on it

**Comment by driftoooo** [comment]
Looking into it. The handling on the M5 F90 is slippy because you're driving it in the snow. When it comes back to normal weather, it'll feel better for you, however, the car does have a learning curve to it. Most people cannot just hop into it and race it around, it takes a lot of learning. As far as the performance mods are concerned, the fix I used for the Jeep is not working on this one so I'm going to continue finding a workaround for this. Hang tight. Thank you for the report.

**Comment by driftoooo** [comment]
Issue fixed - already pushed to live. Thanks again
