### ISSUE TITLE
Removal of PD From "Z Menu"

### ISSUE THREAD

**Issue by BadBritishGamer** [New-Chance-RP/Feedback#696]
<h2>Feature you are requesting.</h2>

The removal of PD visibility on the "Z Menu" when viewing in game.

<h2>What are the benefits to your feature?</h2>

There is no purpose to this, people can rob players when cops are offline so it's not needed for that. The only purpose is criminals using it to metagame and altering their RP to workaround the cops.

It has been noticed whilst on duty for officers that crime severely drops when police are online because they just wait for cops to be offline to commit crime.

<h2>Anything to support your feature request?</h2>

Talk to regular cops who clock in and they will confirm.

**Comment by ChuckBurn** [comment]
Then PD needs to add protocol for police response.. Having 5 police cars racing to a house robbery / drug activity because nobody else doing criminal activity. If it's slow criminal day and someone robs a house I think the first two squad cars to call over dispatch they are responding, should be the only two cars to go unless they call for back up due to seeing criminals with guns. (Also officers just pull up light flashing to the front door of the house hop out and meta game the front door. On a real house robbery you would pull up lights off one cop goes around back and gets eyes on rear escape another would case the front for a few minutes to see if he can see movement in windows. Then get out and check for a break in point before banging on the door and announcing they are on scene.) Not to mention you can't see anything when your in a house and right now it's a coin flip. Either you are scott free or you have 6 cops aiming tazors at the front door screaming don't move hands up. You wouldn't send the entire police force to palito bay for 1 house being robbed, and leave the entire city wide open for criminals. 3 cars for store / 1 for drug / 2 for house. I said car not people so cadets can still ride along and see how it's done.

**Comment by BadBritishGamer** [comment]
@ChuckBurn I appreciate your concern, but this is not related to the feedback post in any way.

As much as I understand your point here there is a place, this is not that place.

If you wish to continue that conversation my DM's are open, but taking digs at the police department in the incorrect place nothing will change.

Thanks.

**Comment by jay2huncho** [comment]
If they remove the Z menu, then they should also slow down how much you guys get notified... It sucks for us, because when we are selling drugs, or doing a house robbery, we don't see a local calling the cops on us. You guys just get automatically notified, and show up, and then we are fucked.

**Comment by BadBritishGamer** [comment]
@jay2huncho Hey, thanks for this input. 

As stated above, this is completely unrelated to the feedback post. If you feel there is an issue with the way cops are receiving notifications then make a feedback post regarding that.

**Comment by Senlarus** [comment]
Some people really hate the cops here. Don't worry, I'll just keep nerfing everything until we can all get along 👍

**Comment by wavyplays** [comment]
I 100% agree with removing the z menu. Irl you wont know how many cops are clocked on, and it should be like that in game aswell. It is really just a metagaming tool for people to start selling drugs when theres no pd on. Same thing can go to ems aswell because people know that theyll get picked up
