### ISSUE TITLE
roadside

### ISSUE THREAD

**Issue by rulefocus2742** [New-Chance-RP/Feedback#727]
<h2>What bug have you found?</h2>

when you message for roadside LSC dont get it from the roadside contact 

<h2>What do you expect should happen?</h2>
really i think that when contacting for roadside it should send a text to LSC so we get notified when someone needs help they dont know to contact LSC for help  
<h2>Anything to support your bug report?</h2>

![Screenshot (399)](https://user-images.githubusercontent.com/68706453/103402747-8c15d600-4b45-11eb-91a0-22d66b25f168.png)

**Comment by driftoooo** [comment]
Correct me if I’m wrong,
But a long time ago there were plans to have a public roadside job for Los Santos Customs, so  that contact may be for the old public roadside job which was removed. Hence why we have the LS Customs contact in which LSC customs contact the LS Customs contact for assistance. In my opinion, for now an easy way to resolve this would be to remove the contact from the phone script if possible until it’s needed again (if it is ever needed again).

**Comment by rulefocus2742** [comment]
yeah i think that we should have it removed from the phone for now as when we get new people in the server there just gunna go to roadside contact

**Comment by Zopfco** [comment]
Dedicated roadside job would be cool but probably not much call for it until the repair rework that was mentioned gets implemented. Might be more of a niche for it when repair kits degrade the vehicle's overall quality (if I understood the plan correctly.)  Could be cool to have the Harmony shop active for this kind of thing.  Then LSC doesn't have to close up shop when they're short staffed in order to go deal with a 4x4 roll-over out in the middle of nowhere.
