### ISSUE TITLE
Economy Balancing/Depression

### ISSUE THREAD

**Issue by 5hallow** [New-Chance-RP/Feedback#746]
<h2>Feature you are requesting.</h2>

As we all know, certain aspects of the economy have taken a hit and have gone into somewhat of a depression (such as the housing market, amongst others) and some aspects are for the better where others are for the worse. Nonetheless, I feel as though if we are going to have a couple aspects of the economy depress, you have to naturally depress the other aspects such as the vehicle market for example. If we are going to depress the economy, we have to go into an actual depression that the entire economy follows in suit instead of just halving the current prices of houses and adding bigger financial barriers in the criminal scene that ultimately slows down money spending - and the flow of money. The car dealership business is so saturated right now, with 3 or 4 dealerships offering imports that new players simply cannot afford given the state of the economy. You then have the issue of long time players selling their imports for far below what the retail of the car actually is, essentially putting all dealerships out of business. Some of the more exotic and rare imports need to be limited and even numbered to maintain their value. All I'm asking for is the economy follow a certain etiquette, if you are going to depress it let's actually depress it and if we are going to inflate it let's actually inflate it. 

Currently, there are not too many methods of making money considering the recent changes so I also think there need to be more methods of making "good" money - for both aspects (criminal and legal).

<h2>What are the benefits to your feature?</h2>

A more stable economy that has a good flow of money circulating.

<h2>Anything to support your feature request?</h2>

Ask people their thoughts on the current state of economy.

**Comment by Zopfco** [comment]
> You then have the issue of long time players selling their imports for far below what the retail of the car actually is, essentially putting all dealerships out of business.

I would argue that this is not an "issue" but actually an example of the market adjustments you're talking about.  The thread about adding a scrap yard made similar complaints about cars listed at the Moto-Market not selling.

In each case (to include housing) the product being sold was overpriced and is finding a real (consensus, shared) value.  When my vehicle wasn't selling, I lowered the price until it did. That's the economy working as intended.

>Some of the more exotic and rare imports need to be limited and even numbered to maintain their value.

Totally agree, plus I don't like the way the local cars became an afterthought when imports were introduced. 

>All I'm asking for is the economy follow a certain etiquette, if you are going to depress it let's actually depress it and if we are going to inflate it let's actually inflate it.

The economy should follow what the market dictates. Some thing will be start off overvalued while others are too cheap.  Since this server is built on a player economy, this isn't a bug. It's an opportunity.

**Comment by Ic3BoxTheSuspect** [comment]
> The economy should follow what the market dictates.

When the market dictates something like this, a manufacturer would cut his prices in order to adjust to the market demand, otherwise he would risk selling nothing.

> When my vehicle wasn't selling, I lowered the price until it did.

So you basically agreed with the main post. If a dealership imports and sells a vehicle for $300,000 and you lowered your price on the same vehicle until you sold it at $100,000 , it basically puts us dealerships out of business. But we can't lower our prices more because we will either make no profit if we sell at import price, or lose money if we lower it more than that.

**Comment by 5hallow** [comment]
Thank you for typing my response out for me - literally. Took the words out of my mouth. When I am importing a SRT Hellcat for $325,000 looking for a profit margin ON TOP of that but 3 people are already selling their fully tuned Hellcats for 250k.. there's an issue. Imports have set prices and when you crash the economy like how they did, and leave manufacturer prices as what they were prior to the economy crash, it simply doesn't line up.

**Comment by Zopfco** [comment]
> When the market dictates something like this, a manufacturer would cut his prices in order to adjust to the market demand, otherwise he would risk selling nothing.
> 

That's true, but the high price of imports is also meant to be a limiting factor by design.  If they're easily affordable for most people, why have local cars for sale beyond a few beaters to drive while saving up for an import?

> If a dealership imports and sells a vehicle for $300,000 and you lowered your price on the same vehicle until you sold it at $100,000 , it basically puts us dealerships out of business. But we can't lower our prices more because we will either make no profit if we sell at import price, or lose money if we lower it more than that.

Sounds harsh but maybe dealerships were a bad investment like other real estate? 

I've seen a few of them come and go now, and what I've noticed about the ones still operating is that they stock a mix of vehicles, cheap used local cars alongside the high end stuff.  The ones that fail had only 1-2 expensive cars in their showroom that sat around for weeks. I would think at some point it's worth selling at cost or even a slight loss just to keep things moving?

**Comment by Senlarus** [comment]
We have changes planned for the economy. This is a multi-stage process and it starts with brining income from drugs more in line with income from higher profile legal jobs like car dealerships, whitelist jobs, and a progression system for the public jobs that can allow people to make more money over time.

We have been discussing and planning these economy changes in leadership for a month now and are starting to roll them out. The housing change was our first step and we will continue to make the changes we have planned out based on the data we have from our database that shows us where the money is coming from, where its being used, and what items are harder/easier to come by.
