### ISSUE TITLE
E63 brabus bugs with kits

### ISSUE THREAD

**Issue by Husk123** [New-Chance-RP/Feedback#763]
<h2>What bug have you found?</h2>

The E63s brabus gets worse with kits on.

<h2>What do you expect should happen?</h2>

The kits should enhance the car but it seems to limit it. ive been told by Dima that without kits he could hit 240, but in the video i can just about go over 200 down hill,
<h2>Anything to support your bug report?</h2>

https://streamable.com/bbz4o6

**Comment by driftoooo** [comment]
I tested these vehicles about 2 days ago, with and without kits on dev, vehicles seem fine. Timed runs were showing a difference, with the kitted vehicle being quicker. Downhill speed can be determined by a multitude of varying factors, including but not limited to: Road surface | Amount of bumps on the road | Number of people in the car etc. etc. When I tested my two, I had one person p/car and I was using the same (at least to the best of my ability) exact part of the road for each test. What you'll notice, is especially when going past pillbox, some cars can rack up to 200 one time and 220-230 another time purely due to the way the physics engine handles a car hitting a bump. Hopefully, this will answer any of the concerns and/or questions you had. Thank you for reporting this :)

**Comment by driftoooo** [comment]
I went ahead and did a trial run, I did 8 pulls past pill-box in each vehicle (One without kits, and one with kits), which will represent the ultimate best-case scenario for these vehicles due to the bumps in the road which will cause the car to hit speeds it wouldn't be able to hit otherwise:

No Kits:
223 mph
225 mph
222 mph
220 mph 
224 mph
226 mph
224 mph
225 mph
Average: 223.625 (Round 0 d.p. -> 224 mph)

Kits:
233 mph
235 mph
230 mph
229 mph
238 mph
237 mph
235 mph
236 mph
Average: 234.125 (Round 0 d.p. -> 234 mph)

Conclusion: 
Kits seem to be working, I'll be closing this issue for now. Thank you again for the report. :)
